### ISSUE TITLE
How to set multiple keys using wininput

### ISSUE THREAD

**Issue by hellishvictor** [cbdevnet/midimonster#104]
Hi, 
How can be set multiple keys (with values in hexadecimal) using the wininput backend? something like **key{0x30..0x5A}** for set keys from 0 to Z.
Cheers

**Comment by cbdevnet** [comment]
Hi @hellishvictor, I'm not sure I understand your intent correctly.

To press multiple keys at once, you can map one input channel to many output channels, for example

```
input-instance.input-channel > wininput-instance.key.{a,b,c,d,e,f}
```

For backends that work with alphanumeric channels names (such as the wininput backend), the range-style multi-channel specification (`x..y`) will only work in some cases, when there is a number in the channel name to be incremented.

The list-style multi-channel specification (`{a,b,c,d}`) will usually be more useful in that case.

**Comment by hellishvictor** [comment]
The idea in essence was to map in a single sentence some keys to some midi notes, like numbers 0 to 9 to midi notes 0 to 9:
`in.key{0x30..0x5A} > out.ch10.note{0..9)`
So for example, if the VK_7 is pressed, it will send a midi note on number 7, which is G-1.

However, for trigger a midi CC toggle with combo key, like Shift+F1, I guess it will something like:
`in.key{shift,f1} > out.ch1.CC7`
Right?

**Comment by hellishvictor** [comment]
The idea was to map in a single sentence some keys to some midi notes, like numbers 0 to 9 to midi notes 0 to 9 (from C-1 to A-1):
in.key{0x30..0x39} > out.ch10.note{0..9)
or also:
in.key{0..9} > out.ch10.note{0..9)
So for example, if the VK_7 is pressed, it will send the midi note number 7, which is G-1.

However, how do I send a midi CC using a combo key (like Shift+F1)? Here is an example:
in.key.{**shift+F1**} > out.ch1.CC7

**Comment by hellishvictor** [comment]
The idea was to map in a single sentence some keys to some midi notes, like numbers 0 to 9 to midi notes 0 to 9 (from C-1 to A-1):
`in.key{0x30..0x39} > out.ch10.note{0..9)`
or also:
`in.key{0..9} > out.ch10.note{0..9)`
So for example, if the VK_7 is pressed, it will send the midi note number 7, which is G-1.

However, how do I send a midi CC using a combo key (like Shift+F1)? Here is an example:
`in.key.{**shift+F1**} > out.ch1.CC7`

**Comment by hellishvictor** [comment]
The idea was to map in a single sentence some keys to some midi notes, like numbers 0 to 9 to midi notes 0 to 9 (from C-1 to A-1):
`in.key{0x30..0x39} > out.ch10.note{0..9)`
or also:
`in.key{0..9} > out.ch10.note{0..9)`
So for example, if the VK_7 is pressed, it will send the midi note number 7, which is G-1.

However, how do I send a midi CC using a combo key (like Shift+F1)? Here is an example:
`in.key.{shift+F1} > out.ch1.CC7`

**Comment by hellishvictor** [comment]
I

> However, how do I send a midi CC using a combo key (like Shift+F1)? Here is an example:
> `in.key.{shift+F1} > out.ch1.CC7`

I'm still waiting for an answers to this: _how do I send a midi CC using a combo key (like Shift+F1)?_
`in.key.{shift+F1} > out.ch1.CC7` doesn't work.
Cheers.
