### ISSUE TITLE
Windows LUA failed to load plugin

### ISSUE THREAD

**Issue by prato-X** [cbdevnet/midimonster#108]
Hello at all,

i tried to install  midimonster Windows (x64 PE)  at 2 different windows10 PC .
 Both installations failed with 
failed to load plugin backends\lua.dll 

lua.dll is present in this directory

I'm happy about an solution

needed for  Mqtt  to Midi  connection

![grafik](https://user-images.githubusercontent.com/72698346/152574966-b7f5ca40-c594-46f9-a549-bd825e9153d3.png)

**Comment by cbdevnet** [comment]
Hi @prato-X, thanks for your interest in the MIDIMonster!

If you don't need the Lua functionality, you can ignore this message and the MIDIMonster will run fine.
If you do need the Lua backend to work, you will need to download an additional library from the creators of the Lua language as described in the [Lua backend documentation](https://github.com/cbdevnet/midimonster/blob/master/backends/lua.md) at the bottom. Note that this is a different file from the `lua.dll` file in the `backends/` folder and will need to be installed one folder above (at the same level as `midimonster.exe`)

Hope that helps!

**Comment by cbdevnet** [comment]
Closing this issue as the question has been answered. If you are still encountering problems, feel free to reopen.
