### ISSUE TITLE
Hang on windows 10 install MM 0.6

### ISSUE THREAD

**Issue by geoffreyplatt** [cbdevnet/midimonster#130]
Hey guys / gals.

I'm having issues installing the latest 0.6 build on Windows 10. Seems like there is a dependency error and descriptor error. Any great solutions out there? Thanks,

 [Midimonster hang](https://user-images.githubusercontent.com/16669773/226998923-a4b820cc-d74f-49fc-9ed6-90e2f862bb35.PNG)

**Comment by Spacelord09** [comment]
Hey, how did you tell its frozen? In the screenshot you're using the default config(With no function).

**Comment by geoffreyplatt** [comment]
Thanks, I didn't read enough and figured there would be a graphical UI to create configurations. I think I understand more now in how the app works. Would be awesome to have a graphical interface though.
