### ISSUE TITLE
Add an OLA backend

### ISSUE THREAD

**Issue by peternewman** [cbdevnet/midimonster#14]
Have you considered adding an OLA backend:
https://github.com/OpenLightingProject/ola

We already support lots of other lighting protocols and it saves you having to reinvent the wheel. We've got a good API to allow integration:
http://docs.openlighting.org/ola/doc/latest/dmx_cpp_client_tutorial.html

**Comment by cbdevnet** [comment]
Sure, sounds like a good idea :) Though I still like to reinvent the wheel sometimes just to have lightweight implementations, fewer dependencies, or just to have had the experience ;)

**Comment by peternewman** [comment]
> Sure, sounds like a good idea :)

Great!

> Though I still like to reinvent the wheel sometimes just to have lightweight implementations, fewer dependencies, or just to have had the experience ;)

Yeah bits of OLA are like that too, although I suspect some of the protocols are too niche to get everyone to reimplement them.

**Comment by cbdevnet** [comment]
Hey, since you seem to be a bit knowledgeable on OLA - do you know how to extract the connection file descriptors from any of the OLA*ClientWrapper classes (Specifically OLACallbackClientWrapper)? Documentation seems to be a bit sparse on that, and delving to deep into C++ projects gives me the willies :P

**Comment by peternewman** [comment]
I assume this is to add it to an existing event loop? There's a bit of info here:
http://docs.openlighting.org/ola/doc/latest/event_driven.html

This is another option:
http://docs.openlighting.org/ola/doc/latest/cpp_client_tutorial.html#cpp_client_Thread

I think you'll want m_socket from here (which doesn't appear to be publicly exposed currently):
https://github.com/OpenLightingProject/ola/blob/d1010976c47de23dc6031749179f8d92596b7e8d/include/ola/client/ClientWrapper.h#L95

What are you trying to do?

**Comment by cbdevnet** [comment]
I'm tinkering with writing an OLA backend, and like you guessed, I'll need to feed the descriptors to the MIDIMonster's event loop :)

**Comment by peternewman** [comment]
Yeah I got excited by that too. I guess no-one has done it yet, or at least they've not shared it/got it added to the docs. I think most integrations have been in Python, apart from QLC+

It's protected, but it just needs a function to access it I think, see GetSelectServer() which accesses a private variable via a public function. It just means you can't do ola_client.m_socket.

**Comment by peternewman** [comment]
So here's how QLC+ does it:
https://github.com/mcallegari/qlcplus/blob/master/plugins/ola/olaoutthread.cpp

**Comment by cbdevnet** [comment]
OK, so I now have an `OLACallbackClient` by bypassing the Wrappers entirely and just constructing it from scratch, the next problem is: How do I notify the client that its socket has been signaled for read?

The `SelectServer` (which I'd rather not use as at that point, it just incurs pointless syscalls) delegates the actual work to `SelectPoller->Poll()`, which via the scenic route delegates the actual reading of data to `ConnectedDescriptor->PerformRead()`, which requires a callback member (`m_on_read`) to be set from somewhere. The function that sets this is defined in the header file (Descriptor.h:221), not in the source file, which resides in a completely different folder and is called `SetOnData`. Now this is called from within `SelectServer` to call `DrainAndExecute`, which does something with `m_incoming_callbacks`, of which I'm not too sure where it's populated from. We'll see...

**Comment by cbdevnet** [comment]
So I just pushed an implementation, it's sorta rough on the edges though most of that I kind of blame on the OLA API. Seems to work though, maybe you can run some more extensive tests?
