### ISSUE TITLE
Is it possible to use lua binary file instead of lua script?

### ISSUE THREAD

**Issue by kimwida** [cbdevnet/midimonster#143]
I run midimonster on my SBC(Rock Pi S : https://shop.allnetchina.cn/products/rock-pi-s) and I want it faster.

**Comment by Spacelord09** [comment]
No, that is not possible. What are you trying to achieve? Midimonster should be fast enough for almost any use case you throw at it.

What does your LUA code do? It could be that its not optimized for speed.


Just as a heads up: Please do not ask the same question in several places(In this case Discord and here). Thank you!
