### ISSUE TITLE
Backend for Testing

### ISSUE THREAD

**Issue by Spacelord09** [cbdevnet/midimonster#23]
@cbdevnet can you add a Backend for testing? that makes "testing" a bit easyer.

The Backend should do a loop from 1 to 127 or from 1 to 255 up and down.. in a specific time.

**Comment by cbdevnet** [comment]
You can do that using the Lua backend - you can register a function to be called periodically, for example to put a sinus value on a channel ([config](https://github.com/cbdevnet/midimonster/blob/master/configs/flying-faders.cfg) and [script](https://github.com/cbdevnet/midimonster/blob/master/configs/flying-faders.lua))
