### ISSUE TITLE
Makefile install target

### ISSUE THREAD

**Issue by cbdevnet** [cbdevnet/midimonster#28]
This has implications for the plugin directory and possibly the default configuration name

**Comment by mxmilkb** [comment]
I'm looking to create a PKGBUILD to install `midimonster` on Arch Linux systems. I'm wondering though where the backend files should be installed to? Usually `make DESTDIR="${pkgdir}" install` would be used. An `install` of specific files to specific locations can be done though.

**Comment by cbdevnet** [comment]
I'd guess  the most appropriate location for the backend plugins would be `${PREFIX}/libexec/midimonster`.

This will have to be set in the Makefile as `PLUGINDIR` (not yet overwriteable from the environment but that should be done).

The default configuration file name is currently set in `midimonster.h` and is not as important (as it would be overwritten from the commandline most of the time), but nevertheless it should probably be made configurable from the build environment and be set to something like `/etc/midimonster.conf` for package builds.

**Comment by cbdevnet** [comment]
I added an `install` target and typed out some documentation on how to set the appropriate environment for a packaging build in the [README](https://github.com/cbdevnet/midimonster#build) :)
