### ISSUE TITLE
MIDI backend: NRPN support

### ISSUE THREAD

**Issue by cbdevnet** [cbdevnet/midimonster#3]

**Comment by cbdevnet** [comment]
NRPN support is sketchy at best in ALSA itself, so unless switching to rawmidi is an option, NRPN support is not going to happen.

Additionally, I failed to procure hardware to properly test any possible implementation, so unless someone has a compelling use case for this, I'm closing the issue.

**Comment by tormodvm** [comment]
@cbdevnet 
> ...so unless someone has a compelling use case for this, I'm closing the issue.

I have a use case for this. On my Tascam us-2400, the faders support 10-bit resolution, in an MSB and LSB setup.  Would be great to have 1024 steps instead of just 128.

**Comment by cbdevnet** [comment]
Hey @tormodvm, thanks for the headsup! Great to hear there's interest in this :)

I'm reopening this and will look into it further.

**Comment by tormodvm** [comment]
I guess I could solve it with a handler in lua or python as well, if I've understood things correctly.

Anyway, great project! 😃

**Comment by cbdevnet** [comment]
I just pushed some changes concerning this issue from my local worktree to GitHub. With commit 35f4798673194733358cd3db19a4d2baf70887fd, NRPNs and RPNs should work with all MIDI backends.

Please reopen this issue if you encounter problems, this functionality is not as well tested as I would like as I don't actually have Hardware that transmits (N)RPNs.
