### ISSUE TITLE
Building question

### ISSUE THREAD

**Issue by bengreenow** [cbdevnet/midimonster#32]
Hey, could you go into a little more detail on how to compile and run this on Windows? - bit of a noob here :) don't really know what im doing but would really love to use this tool. thanks.

**Comment by cbdevnet** [comment]
Hi, great to hear you're interested :)

Windows is not (for various reasons) my primary platform, but interest has always been strong in running the MIDIMonster on it. Currently, to build the Windows binaries, you'll need access to a Linux machine (though a virtual machine works well, too). When starting with a "normal" Debian (or Ubuntu, which is based on Debian and thus very similar), you need to do the following:

* Open a shell
* Become root (`su` or `sudo -s`)
* Install the packages required for building C software using `apt-get install build-essential pkg-config git`
* Install the Windows crosscompiler using `apt-get install mingw-w64`
* Clone the repository using `git clone https://github.com/cbdevnet/midimonster/`
* Go into the folder with `cd midimonster`
* Run `make windows`

This will generate `midimonster.exe` in the project directory and some DLL files in `backends/`.
Copy those to the Windows machine and it should work :) 

Note that some backends have limitations when running on Windows (see the backend documentation for more info).

At some point (hopefully soon), I'll be confident enough to call a `1.0` release of the MIDIMonster, for which binary builds will then also be available from the Github "releases" section.

**Comment by cbdevnet** [comment]
I tried to attach a zipped set of binaries to the issue, but it seems Github won't let me upload ZIP files with executables in them. I've uploaded them to my own server at https://dev.cbcdn.com/midimonster/midimonster-ccde53920cce56c2873c6cf35460fd74518dc79b.zip. The file contains the current `master` version Windows build.

**Comment by cbdevnet** [comment]
Reopening, the Windows build instructions in the README could be better.

**Comment by cbdevnet** [comment]
Heads up: There are now automatic builds for all platforms on the [releases page](https://github.com/cbdevnet/midimonster/releases)
