### ISSUE TITLE
MAweb Output

### ISSUE THREAD

**Issue by scheidleon** [cbdevnet/midimonster#33]
Hello,

I am trying to use midimonster to control Dot2 with an Akai APC20.

Translating Midi commands to Dot2 works mostly fine with a few lua functions (The device transmits NoteOff messages with a velocity of 127, so executors are only turned on, not off).

Right now i am trying to get feedback of Executor status (On/Off), but it seems i can't get a output from the MAweb backend. 
This is my test configuration:
```
[maweb ma]
host = 192.168.48.38
user = remote
password = 

[backend midi]
name = MIDIMonster

[midi apc20]
read = 20:0
write = 20:0

[lua calc]
script = apc20-calc.lua

[map]
ma.page1.button201 > calc.echotest
```

Lua File:
```
function echotest(value)
    print(value)
end
```

If I try this configuration with fader1 instead of executor201 i occasionally get an output of the fader position, but this is also not reliable. Executor201 doesn't output anything.

Greetings from Germany,
Leon

**Comment by cbdevnet** [comment]
Hi Leon,

thanks for the report, I'll try to reproduce it later :)
Regarding the velocity for note-off messages, I didn't realize some hardware actually used that :D I'll add a patch that simply sets the channel value to 0 when receiving a note-off.

**Comment by scheidleon** [comment]
Hi cbdevnet,

thanks for the quick answer!
After some more testing it seems that pressing a Button in the Dot2 Software works quite well and updates the MAweb backend. (I must have done something wrong the last time I checked) Pressing a Button on the Midi Controller also updates the Dot2 software, but doesn't update the Output of `ma.page1.button201` . 

Example:

Works:
_Toggle executor in Software -> Output changes -> LED Updates_

Doesn't work:
_Press Button on Controller -> Dot2 Software updates_ -> Output of `ma.page1.button201` doesn't change -> LED doesn't update

I hope you can understand my problem.

Regarding the noteOff problem i've also made a change in the midi backend since my first post, since my lua script to fix this was quite messy. Here is my patch: https://github.com/scheidleon/midimonster/commit/b4a9721ff7d93dd899eb8e6c64510afaf95cbbca

Please be aware that this is my first time writing any kind of C code, so there could very well be something wrong with this. Maybe this should also be configurable in the config file.

**Comment by cbdevnet** [comment]
Hi Leon,

I think I understand the problem, and I think I know where it comes from, but my hunch is that it's in the feedback elimination for the maweb backend. I'll look into whether it would be useful to remove it for button controls (since feedback elimination mostly concerns faders which change slowly over a range).

Regarding you change, I'd recommend you simply add

```
if(ev->type == SND_SEQ_EVENT_NOTEOFF){
   val.normalised = 0;
}
```
on line 267 of `midi.c` instead of creating a new `case` :)

Maybe you could do a pull request with that, I'd be happy to merge it :)

**Comment by cbdevnet** [comment]
I just pushed a change to the maweb backend that should allow buttons to update their state immediately when being pushed from MIDIMonster, please try with the current `master` :)

**Comment by cbdevnet** [comment]
Confirmed working with dot2

**Comment by scheidleon** [comment]
Hi,

i'm sorry i've been quiet for so long.
I've haven't had the time to test these changes, but will try them out this coming week. 
Again, Thank you for your quick help and keep up the great work!
