### ISSUE TITLE
Install example configs to /usr/share/midimonster/?

### ISSUE THREAD

**Issue by mxmilkb** [cbdevnet/midimonster#35]
So these would be available in the MIDIMonster packages for the user to use or copy.

**Comment by mxmilkb** [comment]
(As in part of the `make install` process.)

**Comment by cbdevnet** [comment]
Implemented in 5b840d986ae723656aad4163e12f7d24a88e1da3

**Comment by Spacelord09** [comment]
Wee need to make this variable. @cbdevnet can you add this as a parameter to the makefile?

**Comment by cbdevnet** [comment]
I'm not sure making the path for 'shared' data configurable is useful, it already respects `PREFIX` correctly. According to the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard), `$(PREFIX)/share` is the correct path for shared data.The other configurable paths are less clear-cut in my opinion, especially for `DEFAULT_CFG` which may or may not be placed in a subdirectory of `$(PREFIX)/etc`.

If there is a compelling case where this functionality would be useful or required, please reopen this issue, I'm closing it for now.
