### ISSUE TITLE
Installer updater symlink does not work.

### ISSUE THREAD

**Issue by Spacelord09** [cbdevnet/midimonster#40]
The UPDATER_SAVE function does save the updater, but the symlink does not work and the name is wrong(/usr/bin/midimonster-updater\n).

**Comment by cbdevnet** [comment]
For future reference, the problem is in https://github.com/cbdevnet/midimonster/blob/a25e815c4d5b4af5068ed3254be8e18c4c4fe7ab/installer.sh#L154
