### ISSUE TITLE
Is it possible to send midi note in lua function

### ISSUE THREAD

**Issue by kimwida** [cbdevnet/midimonster#54]
I just understand how to use lua with midimonster.
I mean how to connect channels.
But is it possible to send midi note in lua function.

> apcmini.ch1.note1 > lua.sendnote1

In function of sendnote1, I want to send specific midi note.

**Comment by cbdevnet** [comment]
Yes, thats possible.

Lua instances can have input channels (when data is coming in, the MIDIMonster calls a corresponding handler function on the lua instance) as well as output channels (where the Lua instance outputs data for other backends).

Lua scripts can generate output events using the `output(channelname, value)` function.

For example, the following script:

```lua
function sendnote(value)
	output("out1", 0.512);
end
```

with the following mapping

```
apcmini.ch1.note1 > lua.sendnote
lua.out1 > apcmini.ch1.note1
```

Will output the MIDI value 65 on `apcmini.ch1.note1` every time that channel sends something.

To run lua functions without having to supply input, you can run the function on repeat using `interval()` (see the lua documentation)

**Comment by kimwida** [comment]
Thank you.
Now I got it.

**Comment by cbdevnet** [comment]
Glad to hear :) Thanks for choosing the MIDIMonster!
