### ISSUE TITLE
Sending midi velocity 

### ISSUE THREAD

**Issue by kimwida** [cbdevnet/midimonster#55]
To turn on red leds of apc mini, I have to send back midi note with velocity 3.
Defaulty, they looks like sending 0(off) and 1(green on).
I read that to access midi data, I need to access ALSA Sequencer.
Any demo source or example that I can get??

**Comment by cbdevnet** [comment]
To see what data is sent over the ALSA sequencer on Linux, you can use the `aseqdump` utility.
For example, I have a Launch Control connected to my computer, and running `aseqdump -p "Launch Control"` I can see what data it is sending.

To see a list of port available for listening with aseqdump, you can use `aconnect -io`.

To send exact MIDI velocities using Lua, you need to remember that the Lua backend only communicates using normalized values (ie., values between `0.0` and `1.0`). To send exact MIDI velocities or control values, you can calculate the normalized value using the formula

```
normalized = velocity / 127
```

**Comment by kimwida** [comment]
Thank you very much.
I works like you said.
It's just wonderful program!!!
