### ISSUE TITLE
OSC Bundle format

### ISSUE THREAD

**Issue by kimwida** [cbdevnet/midimonster#56]
Hi.
I try to receive osc signal from Lemur, convert with midimonster and send sacn signal to Win machine.

Lemur osc controller - ip : 2.1.1.5, osc sender
Linux machine - ip : 2.1.1.4, osc listener
Win machine - ip : 2.1.1.2, sacn receiver

In Lemur source, when a button is pushed, I sent osc signal like this.
`if (button == 1) oscout(0,'/x',1);` //0 is 2.1.1.4 port 8000 osc

In linux midimonster, I convert it to sacn signal and send it to Win machine.
`[backend sacn]`
`bind = 2.1.1.4`

`[sacn sacn_out]`
`universe = 9`
`priority = 100`
`destination = 2.1.1.2`

`[backend osc]`
`detect = on`

`[osc osc_in]`
`bind = 2.1.1.4 8000`
`root = /` 
`/x = f 0.0 1.0 `    // should I have to make "x" directory in / ??

`[map]`
`osc_in./x:1 > sacn_out.1`

I don't have any sacn signal.
Could you help me what's wrong with me??

**Comment by Spacelord09** [comment]
Hello @kimwida
Can you send us the midimonster output when you´re generating events(via osc)?

**Comment by kimwida** [comment]
```
[osc osc_in]
bind = 2.1.1.4 8000
dest = 2.1.1.4 8001

/x = i 0 1

[map]
osc_in./x > feedback.showvalue
```

When I push the Lemur button, midimonster say
"osc Invalid format string in packet for instance osc_in"

**Comment by kimwida** [comment]
Strange.
When I tried your demo codes with Touch OSC, it works but Lemur not...

**Comment by cbdevnet** [comment]
Hey, sorry for the delay, I was a bit busy with work :)

The configuration seems OK, you don't need to specify the root as `/` as that is the default, but then again it doesn't hurt either :)

You don't need to create any additional directories, that's just how OSC names its signals.

So if I'm understanding the Lemur call correctly (I've never used it myself yet, and can't seem to find proper documentation, at least without buying it), the call `oscout(0,'/x',1);` should output on OSC path `/x`, the value `1.0`, is that correct? Could you tell me what the first parameter (`0`) does, just so I understand the setup correctly?

What is conspicuously missing is a format string specification in Lemur, as it seems to be float I'm guessing its `f` and the MIDIMonster should already be able to read that. The message `Invalid format string in packet` comes up when a packet is received and the first byte of the format string is not a comma. The [specification for OSC 1.0](http://opensoundcontrol.org/spec-1_0) says that

> An OSC Type Tag String is an OSC-string beginning with the character ',' (comma) followed by a sequence of characters corresponding exactly to the sequence of OSC Arguments in the given message.

It _could_ be that this was changed in OSC v1.1, as their Website seems to have some broken links currently I can't check that for sure.

Could you maybe do the following for me to analyze the packets from Lemur better:

* Install the `tcpdump` tool on your MIDIMonster computer, for example using `apt-get install tcpdump`
* Run the MIDIMonster
* Run the command `tcpdump -w lemur_osc.pcap`
* Send the command from Lemur until the `Invalid format string in packet` shows up in MIDIMonster
* Stop `tcpdump` by pressing CTRL + C
* tcpdump should write any packets that came in during this time to the file `lemur_osc.pcap`. You can inspect the file with Wireshark to remove packets that may contain information you don't want out in the open for privacy reasons.
* Please attach that recording to this issue so I can take a look at how Lemur formats the OSC data

**Comment by kimwida** [comment]
linux machine ip : 2.1.1.4
ipad mini2 ip : 2.1.1.13
At first event, I push a button on Lemur and second I push a button on Touch OSC.
I set them all to send same osc data "/1/push1","f" and "0.0" or "1.0" which I confirmed it with Resolume osc monitor.
The parameter (`0`) means **OSC Target (communication path to an application)** in their manual page 52. 
I attached the tcpdump file and lemur manual which I ziped in windows.
Thanks for your time.
[lemur_osc.zip](https://github.com/cbdevnet/midimonster/files/4458648/lemur_osc.zip)

**Comment by cbdevnet** [comment]
Thank you for the capture! I see that Lemur is using the Bundle encoding of OSC, which is not yet implemented in MIDIMonster.

I'll try to do that over the next few days :)

**Comment by kimwida** [comment]
Great!! I am looking forward to it and ready to test it.

**Comment by cbdevnet** [comment]
Please try again with the latest master, I tried with the packet from the capture and I think it should work :)

**Comment by kimwida** [comment]
I did `midimonster-updater`.
`The installed version **MIDIMonster v0.4-29-gdaf9ac5** seems to be up to date
Doing nothing`

Then I tested it and got same result with Lemur.
I think it didn't update, did it?

**Comment by Spacelord09** [comment]
Hey @Kimwida, did you try running the updater with the --forceupdate argument?

**Comment by Spacelord09** [comment]
If that doesn't work, please try the following to force an update to the nightly version:
midimonster-updater --dev --forceupdate

**Comment by kimwida** [comment]
Wow!!!
It works!! Thanks guys!!!
