### ISSUE TITLE
Windows input devices backend

### ISSUE THREAD

**Issue by sherify2011** [cbdevnet/midimonster#57]
I want to congratulate you on your software. It is such a wonderful and handy app for entertainment technology practitioners!
I want to find out if there's a way to have PC hotkeyed/keypress. If it does, how?

Thanks in anticipation for your reply.

**Comment by cbdevnet** [comment]
Hi @sherify2011, thanks for your kind words :) I'm always happy to hear that people like the MIDIMonster!

On Linux, you can use key presses/releases, joystick and mouse inputs as input and output channels. To build hot-key recognition across multiple keystrokes from that, you could use the Lua or Python backends to program additional logic.
You can even distinguish between multiple connected devices to read from, for example to connect an additional keyboard only for your controller.

There are example configurations for [controlling ArtNet from a gamepad](https://github.com/cbdevnet/midimonster/blob/master/configs/evdev.cfg) and [controlling the mouse using a MIDI controller](https://github.com/cbdevnet/midimonster/blob/master/configs/midi-mouse.cfg).

To read key presses, you can use the syntax `instance.EV_KEY.KEY_A` for example, more information is available in the [`evdev` backend documentation](https://github.com/cbdevnet/midimonster/blob/master/backends/evdev.md). To see the devices connected to your computer and what keys/axes they support, you can use the `evtest` tool.

On Windows, keyboard/mouse input and output are not yet supported but may be in the future if there is sufficient interest and motivation :)

**Comment by sherify2011** [comment]
It absolutely answer the question. Yes I'm asking for the possibility on Windows. Thanks for your answer.

**Comment by cbdevnet** [comment]
I'll use this ticket to track development on this, it might be some time until I get to implementing it, but I'll keep you up-to-date via this thread :)

**Comment by cbdevnet** [comment]
The backend seems to work quite well, please open an Issue if you find a bug :)
I might additionally implement joystick input in the near future, we'll see.

**Comment by sherify2011** [comment]
@cbdevnet how do I test the wininput on Windows?

**Comment by Spacelord09** [comment]
Hey @sherify2011
You can look at https://github.com/cbdevnet/midimonster/blob/faf34959ee4a86441bc3e96229fbd5365869d523/backends/wininput.md

**Comment by cbdevnet** [comment]
Hi @sherify2011 
I have uploaded a compiled development version for Windows containing the wininput backend on https://files.midimonster.net/midimonster-v0.5-6-gfaf3495-windows.zip

**Comment by sherify2011** [comment]
I will check and revert back

**Comment by sherify2011** [comment]
The backend indeed works well.
But for keys input such as 'Control C', is there a way to have such input mapped?

**Comment by cbdevnet** [comment]
Hi @sherify2011,
mapping key combinations directly is currently not supported directly, but this can be done with a simple Lua script and mapping the component channels to a Lua instance, for example.

MIDIMonster config
```
[wininput win]

[lua hotkey]
script = hotkey.lua

[map]
win.c > hotkey.c
win.ctrl > hotkey.ctrl
hotkey.ctrlc > <your target>
```

hotkey.lua
```lua
function c(value)
	if(input_value("ctrl") + input_value("c") == 2.0) then
		output("ctrlc", 1);
	else
		output("ctrlc", 0);
	end
end

function ctrl(value)
	if(input_value("ctrl") + input_value("c") == 2.0) then
		output("ctrlc", 1);
	else
		output("ctrlc", 0);
	end
end
```

**Comment by sherify2011** [comment]
Ok.
But I'm taking intern of winmidi to wininput map i.e.
**map**
** bcf.ch9.note1  <> input.key.control **

So for **control c** I used:
** bcf.ch9.note1  <> input.key.control **
** bcf.ch9.note1  <> input.key.c**

And it works. But I want to find out if there's other ways to do it.

**Comment by cbdevnet** [comment]
Ah OK, I thought you wanted hotkey detection - for pressing Ctrl+C, just map the same input channel as you discovered already :)
