### ISSUE TITLE
Run a lua function without any trigger

### ISSUE THREAD

**Issue by kimwida** [cbdevnet/midimonster#58]
Hi.
I want to set my launch control's pads some colors when midimonster starts.
You can think that it is like initialazation and I want to run a lua function without any trigger.
I mean I can set my launch control's pads some colors on but at least it needs a event like a pad pushing.

This show how I set colors on my launch control's pads. When I click a pad on my iphone, it trigger lua function.

midimonster.cfg
> osc_iPhone./x1 > feedback.getin
> feedback.getout{1..4} > launch_control.ch5.note{5..8}
 
demo.cfg
>function getin(value)
>        output("getout1",60/127)
>        output("getout2",60/127)
>        output("getout3",60/127)
>        output("getout4",3/127)
>end

But I want to do it without click iphone's pad. Any ideas?

**Comment by cbdevnet** [comment]
Hi,

with commit  d1baab6ce4b13c562867147ed60906dfe651ae81, you can simply add top-level `output` statements to your scripts. These will be executed at load time and the values will be cached and output when processing begins.

For example, the script

```lua
function input(value)
   print("Input is at " .. value)
end

output("out1", 0.75)
```

will set the `out1` channel to the normalized value 0.75 at startup.

**Comment by kimwida** [comment]
Thank you!
It works!

**Comment by cbdevnet** [comment]
Alternatively, you could also make a function that executes every `n` milliseconds using the `interval()` API in the Lua backend, or create a Lua thread to output your values using the `thread()` and `sleep()` APIs :)

**Comment by kimwida** [comment]
Actually, I am not a professional programmer and it was very hard for me to understand the lua backend demo codes. Still I don't understand interval(), thread() and sleep() things. :) But I am very happy with your program and manage to implement what I want.

**Comment by cbdevnet** [comment]
Thank you for reporting that, writing good documentation is a hard thing to do! 

Sometimes it can be hard to choose what to include and what to keep out so readers don't get bored or overwehelmed by information - this is especially hard when you have to transmit a lot of information in a relatively short document.

I will try to extend the example code and descriptions in the Lua documentation to hopefully make it easier to understand. I'm also planning to produce some videos on the MIDIMonster, including a more detailed explanation of programming using the Lua backend, but this will still take some time to do :)
