### ISSUE TITLE
Configuration file 'include' directive

### ISSUE THREAD

**Issue by kimwida** [cbdevnet/midimonster#59]
Hi.
I am testing lots of midi controllers and some macro keyboards.
The more devices I test, the bigger midimonster.cfg is.
So I wonder I could use like this or not.

> [map]
> #include "keyboard.map"
> #include "apcmini.map"

**Comment by cbdevnet** [comment]
Hi @kimwida,

This is not yet implemented, but I will add it soon :) Will update you here then!

**Comment by cbdevnet** [comment]
Should work with the latest `master` using the syntax

`
[include other/file.cfg]
`

**Comment by kimwida** [comment]
Thanks, it works perfect!!

**Comment by sherify2011** [comment]
@kimwida, does it work with winmidi backed (Windows) and how do I configure it?

**Comment by kimwida** [comment]
@sherify2011, I am using it with linux. I think @cbdevnet will upload new winmidi backed release soon.
https://github.com/cbdevnet/midimonster/releases

**Comment by sherify2011** [comment]
Ok. Thanks for your reply.

**Comment by cbdevnet** [comment]
Hi @sherify2011,

yes, this will also work on Windows and will be included in the next release. You can use it before then if you're willing to build from the current development status for yourself, as [explained in the README](https://github.com/cbdevnet/midimonster#building-for-windows).
