### ISSUE TITLE
maweb logout

### ISSUE THREAD

**Issue by GralfR** [cbdevnet/midimonster#61]
Hi!

I tried midimonster 0.5 for windows with a MA2onPC and a BCF2000. Great job, cbdevnet! This is the only app that has a real fader feedback for MA2. Thank you so much!

Exploring all the options need to restart midimonster each time to reload the config. This is not bad, but stopping midimonster stills blocks one MA2 remote-slot, which is limited to 3 logins.

Midimonster should logout/end the connection to the MA2 when stopping (I pressed Ctrl-C. Is this the correct way?)
If I compare to an Internet Explorer beeing connected as a webremote to the same MA2 onPC and beeing logged in, the Internet Explorer frees the used slot when beeing closed without logout (which nobody does on webremote).
You can see inside the MA2 unter Setup/User-Profiles how many users are logged in. This number is increasing with each restart of Midimonster.

Thanks

**Comment by cbdevnet** [comment]
Hey @GralfR, very glad you like the tool, thanks for your feedback!

Yes, currently the configuration and map is fixed at run-time, I will explore options to change this at some point after the 1.0 release is done :) There are also tentative plans of creating a UI as an additional commercial offering, but that is still further out.

Good point on the log-out though, I will look into that in the next few days and will update you here then.

**Comment by cbdevnet** [comment]
The backend will now send a message to the console terminating the webremote session before disconnecting
