### ISSUE TITLE
maweb Session ID

### ISSUE THREAD

**Issue by GralfR** [cbdevnet/midimonster#62]
Hi!

Running Midimonster 0.5 on windows connected to a MA2 onPC.
The midimonster prints repeatedly something like "session ID is now...".
This is wrong.
The shown number is not the session ID, which a MA-user obviously knows. This seams to be the webremote-commandline ID, which is shown in the MA2 system monitor when starting the midimonster.

So, this might confuse the user. Maybe You like to change that message?

Thanks

**Comment by cbdevnet** [comment]
The field in the API is called "session", though. The message is admittedly printed a lot up to v0.5, with  commit 100b8f2ea0f269094331ee39699ef5fb3e571584 (will be in the next release) it should only print when the console informs the MIDIMonster of a change (which happens sometimes for strange reasons).

I think the term 'session' is used in multiple contexts, event within the MA code itself, and what the manual (and parts of the UI) call a session is different from what the API calls a session, which in turn is different from what MA-NET calls a session.

I'm open to changing the message though, what would you suggest?

**Comment by GralfR** [comment]
Wow, that's a fast reply!

Well, if I have a look at the MA2 System Monitor when starting midimonster with a connection, the MA2 System Monitor prints several lines starting with "webserver" like:
# new WEB_CMDLINE
# CreateSessionResponse new commandline id = 3
# WEB prompt cahnged to...

This id = 3 is what midimonster reports as Session ID. So, I'd suggest to call this a "webremote-session" to distinguish from the MA-net-Session, which has another ID.

**Comment by cbdevnet** [comment]
I was just browsing github anyway so I saw the notifications pop up ;)

OK, I'll change it later this evening :)
