### ISSUE TITLE
Make it possible to give array of values and not just incrementation

### ISSUE THREAD

**Issue by tormodvm** [cbdevnet/midimonster#67]
I have a midi device that has it's buttons layed out like this:

```
cc0 = track 0 - fadertouch
cc1 = track 0 - select
cc2 = track 0 - solo
cc3 = track 0 - mute
cc4 = track 1 - fadertouch
cc5 = track 1 - select
cc6 = track 1 - solo
cc7 = track 1 - mute
cc8 = track 2 - fadertouch
cc9 = track 2 - select
and so on...
```
This makes it hard to map since I can't use incrementation.

Since we already have `{0..10}`,
can we also have `[0,4,8,12]`?

**Comment by cbdevnet** [comment]
Hey @tormodvm, thanks for the suggestion!

I'll look into it, its definitely possible but I will have to see with what effort.

Internally, the config_glob family will have to be extended with a type attribute and new parsing functions for additional glob types.

**Comment by tormodvm** [comment]
Thanks for the quick reply. :) Fingers crossed that it's doable.

**Comment by tormodvm** [comment]
This is great! Good job! 😄 
Can't wait to try it out.
