### ISSUE TITLE
Multiple sACN listeners on different VLANs

### ISSUE THREAD

**Issue by GralfR** [cbdevnet/midimonster#69]
Hi!

I have a Windows system with Intel NIC and several VLANs on this system. The intel driver creates one virtual NIC for each VLAN. All virtual NIC get the same MAC adress as the hardware. This causes problems in MidiMonster binding to the desired network.
In my config is:
`[backend sacn]
bind = 192.168.12.93 5568`

All my NICs/VLANs have static IP. So I expected Midimonster to bind to my adapter with IP 192.168.12.93 and receive sACN.

This only works, if the desired adapter has the highest metric of all active adapters. So, if I set the desired adapter to a manual metric of 1, sACN is received. If I use autometric, no sACN is received.
I do not know how MidiMonster searches for network connections, but if I define an IP to bind to, I expect the program to bind to this IP. If in any case the MACadress is considered, this will not work, 'cause of duplicated MAC-adresses.
This is a problem, many programs face but everybody I reported this to, was able to fix this e.g. by considering MAC, IP and Name to identify the NIC to bind to.

This problem can be confirmed with virtual maschines, where you can change the MAC-adress of all the adapters.

Thanks
Gralf

**Comment by cbdevnet** [comment]
Hi @GralfR, thank you for the bug report and investigation!

For reference, sACN sockets are created at https://github.com/cbdevnet/midimonster/blob/master/backends/sacn.c#L83 using the libmmbackend socket abstraction at https://github.com/cbdevnet/midimonster/blob/master/backends/libmmbackend.c#L141, i.e. the socket should bind on the provided IP-Adress as expected. This problem may have something to do with the Windows handling of multicast data.

Can I ask if you are using multicast or unicast input with sACN? Is possible, could you try if the same effect is seen with the ArtNet backend (This one has similar broadcast capabilities, but does not listen on multicast)?

I will try to replicate the situation and investigate further!

**Comment by GralfR** [comment]
Hi!
I'm using Multicast-Input for sACN. I've also looked into the packages with wireshark on the desired IP/NIC. Wireshark grabbed the packages correctly.
I will try Artnet later this evening.
For reference: the Program sACNview just fixed the same problem in the current release 2.1.1: [https://github.com/docsteer/sacnview/issues/192](url)

**Comment by cbdevnet** [comment]
Thanks for the link, it should be helpful :)

**Comment by cbdevnet** [comment]
After some thought I think I know what's going on and I think it is indeed related to multicast input handling.

The multicast group for the specified universe is joined on https://github.com/cbdevnet/midimonster/blob/master/backends/sacn.c#L645, but we're currently not setting the `imr_interface` member of the `ip_mreq` structure, so all listeners join the multicast group of the primary interface. That obviously doesn't work so well when using multiple interfaces.

**Comment by GralfR** [comment]
I've just testet artnet on the same system. Artnet is working correctly with several active interfaces. So right, multicast seams to be the problem.

**Comment by cbdevnet** [comment]
Could you please try again with the latest commit, hopefully that allows the sACN input to be collected on the specific interfaces.
I've uploaded a Windows build with the commit at https://files.midimonster.net/develop/midimonster-v0.5-27-g4e7acb3-windows.zip for your convenience.

**Comment by GralfR** [comment]
Yes, the 0.5.27 works with sACN Multicast on Windows 7 with several NICs/VLANs.
Thanks for the quick fix!
