### ISSUE TITLE
LUA on Windows 

### ISSUE THREAD

**Issue by comebacktomorrow** [cbdevnet/midimonster#71]
I've tried both the binary release and compiling my own version of both midimonster and lua.dll and have ended up with the same with both approaches. "Failed to load plugin backends\lua.dll, check that all supporting libraries are present: %1 is not a valid Win32 application.".

To the best of my knowledge, I have followed the instructions correctly - lua53.dll is in the midi monster root directory. 

Any help would be amazing.

**Comment by cbdevnet** [comment]
Can I ask you a few details on your setup?

* What version of MIDIMonster are you running (shows up when you run `midimonster.exe -v`)
* What Windows release are you using? 32 or 64 bit?
* What Lua package did you download (presumably from luabinaries)?

I've had similar problems with some builds from luabinaries, for reference on my Windows 7 x64 VM with MIDIMonster 0.5, using the [luabinaries 5.3.5 x64 "MinGW 6" DLL build](https://sourceforge.net/projects/luabinaries/files/5.3.5/Windows%20Libraries/Dynamic/lua-5.3.5_Win64_dllw6_lib.zip/download) works (copying the lua53.dll from the zip next to `midimonster.exe`).

**Comment by comebacktomorrow** [comment]
I think I figured it out - I must downloaded the wrong build of LuaBinaries somewhere along the way. I thought I double checked that. Anyway, I can confirm that lua is working for me with maweb-flying-faders config.
