### ISSUE TITLE
Transmit midi between two devices

### ISSUE THREAD

**Issue by hellishvictor** [cbdevnet/midimonster#78]
Hi, here is my monster.cfg:
```
	[backend winmidi]

	[winmidi midi]
	read = 0 (loopmidi_1)
	write = 2 (loopmidi_2)

	[map]
```
That should transmit midi between two ports since "read" and "write" are assigned to different ports, and the tag "map" is empty (like midi-ox does when selecting devices for input and output); but for achive that, I have to add lines for all the 16 channels:
```
[map]
midi.ch0.cc{0..127} > midi.ch0.cc{0..127}
midi.ch1.cc{0..127} > midi.ch1.cc{0..127}
```
etc.

And I wonder, there's something I'm missing?
Cheers.

**Comment by cbdevnet** [comment]
Hi @hellishvictor,

the `read` and `write` instance configuration options connect that instance's input and output to the specified MIDI port. This only gets the data into the MIDIMonster and makes it available for the actual mapping there - which you do with the `[map]` section :)

So the `read = 0` makes all input coming from the MIDI port 0 available on the MIDIMonster channels, and the `write = 2` makes output sent to those MIDIMonster channels go to that MIDI port. This extra configuration is what allows the MIDIMonster to support translating between the wide array of different supported protocols.

You can further shorten the config to simply copy your input to your output by using multiple multi-map expressions in one mapping like so:

```
[map]
midi.ch{0..16}.cc{0..127} > midi.ch{0..16}.cc{0..127}
```

Hope that answers your question!

**Comment by hellishvictor** [comment]
`midi.ch{0..15}.cc{0..127} > midi.ch{0..15}.cc{0..127}`
Yeah, that is exactly what I looking for, you're a genius!

Cheers.
