### ISSUE TITLE
`midi` backend option naming / program change feature

### ISSUE THREAD

**Issue by hellishvictor** [cbdevnet/midimonster#79]
Here is a couple of features that would be a great implementation on midimonster:
· Support for "Program Change".
· Replace "read" and "write" with "source" and "target".

Cheers

**Comment by cbdevnet** [comment]
Hey @hellishvictor, thanks for your suggestions!

I'll look into the program change control over the next few days :)

As for `read` and `write`, I agree that they might be misunderstood. However, I'm not sure whether `source` and `target` are easier to understand. I think I'll add them as aliases for `read` and `write` respectively, for the time being :)

**Comment by hellishvictor** [comment]
> 
> 
> Hey @hellishvictor, thanks for your suggestions!
Your're welcome @cbdevnet !

> 
> I'll look into the program change control over the next few days :)
> 
That sounds great, look forward for that update +1: 

> As for `read` and `write`, I agree that they might be misunderstood. However, I'm not sure whether `source` and `target` are easier to understand. I think I'll add them as aliases for `read` and `write` respectively, for the time being :)
Thank you! You can't go wront using "in" (or "input") and "out" (or "output"). definelly :)

**Comment by cbdevnet** [comment]
I just pushed some of my worktree changes concerning this issue to github, please reopen the ticket if you encounter an issue with the new program change functionality.
