### ISSUE TITLE
Running as windows service

### ISSUE THREAD

**Issue by alexbst** [cbdevnet/midimonster#92]
Can be run as windows service ?

**Comment by cbdevnet** [comment]
Hi @alexbst, thanks for your interest in the MIDIMonster!

Once you have set up the configuration to your liking, the MIDIMonster can be run without user input, so it should also work as a service. I'm can't really help with setting that up though, I personally don't have a Windows machine here to test.

Hope that helps

**Comment by Spacelord09** [comment]
Hi @alexbst ,
you can try the following command:
```sc.exe create <new_service_name> binPath= "<path_to_the_service_executable>"```

You can find more informations at: [https://support.microsoft.com/kb/251192](Microsoft KB)

I'm closing this for now. If you have further questions just ask here ;)
