### ISSUE TITLE
Map a single event to a multiple of events?

### ISSUE THREAD

**Issue by cjunekim** [cbdevnet/midimonster#96]
Hello.

Is it possible to map a single event to a multiple of events?

For example, I'd like to map a single MIDI CC message into a two OSC messages. Is it possible without resorting to lua/python scripting?

**Comment by phedders** [comment]
On Mon, 2021-08-16 at 03:24 -0700, cjunekim wrote:
> Hello.
> Is it possible to map a single event to a multiple of events?
> For example, I'd like to map a single MIDI CC message into a two OSC
> messages. Is it possible without resorting to lua/python scripting?
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

You can add as many maps for any input as you like.

mididev.cc0 > osc./foo/bar
mididev.cc0 > osc./wibble

**Comment by Spacelord09** [comment]
Hello @cjunekim, glad you like our project!
you can map every channel as many times as you want like:
midi.cc0 > midiout.cc0
midi.cc0 > midiout.cc1
Im going to close this Issue now. If you still have questions feel free to open a new Issue.

**Comment by cbdevnet** [comment]
Hi @cjunekim, as @phedders said, mapping inputs to multiple outputs is well supported :)

You can also map multiple inputs to one output, this will make the output channel act as a `latest-takes-precedence` bus. This is where it gets more complex, as you would need Lua to change that. Again, mapping one input to many outputs is no problem.

I'll add a few sentences to the README regarding this soon, as currently it is implied but not explicitly set down there :)

**Comment by cjunekim** [comment]
> Hi @cjunekim, as @phedders said, mapping inputs to multiple outputs is well supported :)
> 
> You can also map multiple inputs to one output, this will make the output channel act as a `latest-takes-precedence` bus. This is where it gets more complex, as you would need Lua to change that. Again, mapping one input to many outputs is no problem.
> 
> I'll add a few sentences to the README regarding this soon, as currently it is implied but not explicitly set down there :)

Thanks. In one to many mapping, is the order deterministic?

For instance, in @phedders and @ Spacelord09 's example, do they occur in sequence in the order of the previous defined mapping firing first always?

Also, many to one mapping seems a bit vague to me. For example, I want midi cc50 firing once when osc /foo/bar and osc /foo/boo has occured in order.

Would the following do that?

```
osc./foo/bar > midiout.cc50
osc./foo/boo >midiout.cc50

```

**Comment by cbdevnet** [comment]
When mapping one input to multiple outputs, the delivery of all events to the mapped backends is performed in one "core iteration" (which is normally very quick / "as fast as possible").. 

Every backend that is concerned with that mapping gets one call with all the mapped channels (per core iteration). Currently, this results in a somewhat deterministic sequence of packets transmitted, though I'm reluctant to fully commit on that (I may need to implement some sorting/deduplication or similar in the core event queueing at some point, so I'm not willing to make that part of the "software contract").

I would probably be OK with committing to the order being stable, as in the ordering you see once is always going to be the ordering in this running instance. For most intents and purposes, the delay between the two messages will not be relevant on the receiving side.

As for the second question, that config would output events  as they come in on both OSC channels, ie. incoming events on both  channels will transmit matching events on the output channel. These will be ordered wrt to the timing they come in on (down to the core iteration).

**Comment by cjunekim** [comment]
> When mapping one input to multiple outputs, the delivery of all events to the mapped backends is performed in one "core iteration" (which is normally very quick / "as fast as possible").
> 
> Every backend that is concerned with that mapping gets one call with all the mapped channels (per core iteration). Currently, this results in a somewhat deterministic sequence of packets transmitted, though I'm reluctant to fully commit on that (I may need to implement some sorting/deduplication or similar in the core event queueing at some point, so I'm not willing to make that part of the "software contract").
> 
> I would probably be OK with committing to the order being stable, as in the ordering you see once is always going to be the ordering in this running instance (provided the events are processed within the same core iteration). For most intents and purposes, the delay between two messages processed in one core iteration is negligible / not visible on the receiving side.
> 
> As for the second question, that config would output events as they come in on both OSC channels, ie. incoming events on both channels will transmit matching events on the output channel. These will be ordered wrt to the timing they come in on (down to the core iteration). It is pretty unlikely (though not impossible) to get two events into the same core iteration from a "natural" source (ie. something that's not a synthetic event source/a scripted generator of some kind). If that happens, the output will have two events, with the order not being guaranteed.

Thanks. Then, it means many to many. Many to one mapping isn't possible currently(of course, without scripting)?

**Comment by cbdevnet** [comment]
Yes, if you need event processing beyond simply sending both incoming events on the "merged" channel, you will need the scripting capabilities.
