### ISSUE TITLE
Is it possible to use a relative (UDEV) key like "volume-up" to translate into midi and/or CV?

### ISSUE THREAD

**Issue by capoei** [cbdevnet/midimonster#97]
I would like to use the media keys on my keyboard to control volume relativly

**Comment by cbdevnet** [comment]
Is the key itself relative? Normally, media keys come in as absolute keypresses (ie. `button down`, `button up`). You combine those with the Lua (or Python) backend to control an output channel.

One example configuration could be:

```
[evdev in]
input = Keyboard Name

[midi out]
write = MIDI Device name

[lua volume]
script = volume.lua

[map]
in.EV_KEY.KEY_VOLUMEUP > volume.up
in.EV_KEY.KEY_VOLUMEDOWN > volume.down
volume.out > out.ch0.cc0
```

with the Lua script (`volume.lua`) looking similar to

```
current_volume = 0.5
function up()
 if current_volume < 1.0 then
  current_volume = current_volume + 0.1
 end
 output("out", current_volume)
end

function down()
 if current_volume > 0.0 then
  current_volume = current_volume - 0.1
 end
 output("out", current_volume)
end
```

**Comment by cbdevnet** [comment]
I'm marking this as closed for now, feel free to reopen if I misunderstood your question :)
